# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ColorBuilding
                                 A QGIS plugin
 want to color building more than one neighbor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-19
        copyright            : (C) 2024 by MdRaisulIslam
        email                : 32ismd1mpg@hft-stuttgart.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'MdRaisulIslam'
__date__ = '2024-10-19'
__copyright__ = '(C) 2024 by MdRaisulIslam'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ColorBuilding class from file ColorBuilding.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .colorbuilding import ColorBuildingPlugin
    return ColorBuildingPlugin()
